version: "3.1"
services:
  pgcheckout:
    image: postgres:15.1
    environment:
      POSTGRES_DB: checkout
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
#    ports:
#      - "5432:5432"
    volumes:
      - ./data/checkout:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      # noinspection ComposeUnknownKeys
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
  pgbcheckout:
    image: edoburu/pgbouncer
    environment:
      DATABASE_URL: postgres://user:password@pgcheckout:5432/checkout
      AUTH_TYPE: plain
    ports:
      - "5432:5432"
    depends_on:
      - pgcheckout
#  pgbcheckout:
#    image: vapet/odyssey:test
#    ports:
#      - "5432:6432"
#    volumes:
#      - ./checkout/odyssey.conf:/odyssey.conf
#    depends_on:
#      - pgcheckout
  checkout:
    image: checkout
    build: ./checkout/
    environment:
      DATABASE_URL: postgres://user:password@pgbcheckout:5432/checkout
    ports:
      - "8080:8080"
    depends_on:
      - pgbcheckout
  pgloms:
    image: postgres:15.1
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
#    ports:
#      - "5433:5432"
    volumes:
      - ./data/loms:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      # noinspection ComposeUnknownKeys
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
#  pgbloms:
#    image: edoburu/pgbouncer
#    environment:
#      DATABASE_URL: postgres://user:password@pgloms:5432/loms
#      AUTH_TYPE: plain
#    ports:
#      - "5433:5432"
#    depends_on:
#      - pgloms
  pgbloms:
    image: vapet/odyssey:test
    ports:
      - "5433:6432"
    volumes:
      - ./loms/odyssey.conf:/odyssey.conf
    depends_on:
      - pgloms
  loms:
    image: loms
    build: ./loms/
    environment:
      DATABASE_URL: postgres://user:password@pgbloms:5432/loms?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - pgbloms
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
