-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS outbox
(
    msgID           int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    key             varchar,
    message         varchar,
    CONSTRAINT outbox_pk
        PRIMARY KEY (msgID)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS outbox;
-- +goose StatementEnd
